-- ============================================================
-- Esquema de Base de Datos para Calculadora en Supabase
-- Proyecto: https://plfqgprrhgewvztjbikp.supabase.co
-- ============================================================

-- 1. Crear la tabla de cálculos / historial
create table if not exists public.calculations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  expression text not null,
  result text not null
);

-- 2. Habilitar Row Level Security (RLS)
alter table public.calculations enable row level security;

-- 3. Crear políticas para acceso anónimo (lectura, inserción y borrado)
create policy "Permitir lectura publica"
  on public.calculations
  for select
  using (true);

create policy "Permitir insercion publica"
  on public.calculations
  for insert
  with check (true);

create policy "Permitir eliminacion publica"
  on public.calculations
  for delete
  using (true);
